name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Code Download karna
        uses: actions/checkout@v4

      - name: 2. Python Setup karna
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Zaroori Linux Tools Install karna
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libtool pkg-config autoconf automake zip unzip openjdk-17-jdk libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer virtualenv "Cython<3.0"

      - name: 4. APK Banana
        run: |
          # Pehle purana cache saaf karo
          buildozer clean
          # Ab build shuru karo
          yes | buildozer -v android debug

      - name: 5. APK ko Save karna
        uses: actions/upload-artifact@v4
        with:
          name: AI-Prompt-Gallery-APK
          path: bin/*.apk
