[app]
title = AI Prompt Gallery
package.name = aipromptgallery
package.domain = org.mdarman

source.dir = .
source.include_exts = py,kv,png,jpg,jpeg,json,atlas,ttf,otf
source.exclude_dirs = tests,bin,.buildozer,.git,.github,__pycache__

version = 0.1
author = Md Arman

requirements = python3,kivy==2.3.0,kivymd==1.2.0,pillow,requests,pyjnius

orientation = portrait
fullscreen = 0

icon.filename = assets/icon.png
presplash.filename = assets/splash.png
android.presplash_color = #0D0D14

android.permissions = INTERNET

android.api = 33
android.minapi = 24
android.ndk = 25b
android.accept_sdk_license = True

android.archs = arm64-v8a, armeabi-v7a

android.enable_androidx = True
android.allow_backup = True

# Uncomment only if you get AndroidX duplicate class errors
# android.gradle_dependencies = androidx.browser:browser:1.7.0

[buildozer]
log_level = 2
warn_on_root = 1
